/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import BEANS.ChuyenThietBi;
import BEANS.Phong;
import BEANS.QuanLyThietBi;
import BEANS.ThietBi;
import Controller.ChuyenThietBiService;
import Controller.PhongService;
import Controller.QuanLyThietBiService;
import Controller.ThietBiService;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ChuyenThietBiJframe extends javax.swing.JFrame {
    ThietBiService thietBiService;
    List<ThietBi> listTB;
    ThietBi tB;
    
    ChuyenThietBiService chuyenThietBiService;
    List<ChuyenThietBi> listCTB;
    ChuyenThietBi cTB;
    
    PhongService phongService;
    List<Phong> listPhong;
    
    QuanLyThietBiService quanLyThietBiService;
    QuanLyThietBi qLTB;
    List<QuanLyThietBi> listQLTB;
    
    DefaultTableModel defaultCTBModel;
    
    String maTB;
    String maQL;
    int maPhong;
    SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
    /**
     * Creates new form ChuyenThietBiJframe
     */
    public ChuyenThietBiJframe(String maTB1, String maQL1, int maPhong1) {
        initComponents();
        maTB = maTB1;
        maQL = maQL1;
        maPhong = maPhong1;
        thietLapBanDau();
        setTableCTB();
    }
    
    private void setTableCTB() {
        defaultCTBModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        chuyenTBTable.setModel(defaultCTBModel);
        
        defaultCTBModel.addColumn("Mã Phiểu");
        defaultCTBModel.addColumn("Mã P Cũ");
        defaultCTBModel.addColumn("Mã TB");
        defaultCTBModel.addColumn("Số Lượng");
        defaultCTBModel.addColumn("Mã P Mới");
        defaultCTBModel.addColumn("Ghi Chú");
        defaultCTBModel.addColumn("Ngày Chuyển");
        
        setDataCTB(chuyenThietBiService.getAllChuyenTBs());
        
    }
    
    private void setDataCTB(List<ChuyenThietBi> listCTB) {
        defaultCTBModel.setRowCount(0);
        listCTB.forEach(ctb -> {
            defaultCTBModel.addRow(new Object[] {
                ctb.getMaPhieu(), ctb.getMaPhongCu(), ctb.getMaTB(), ctb.getSoLuong(), ctb.getMaPhongMoi(), ctb.getGhiChu(), ctb.getNgayChuyen()
            });
        });
    }
    
    private int setNewMaPhieu(List<ChuyenThietBi> listCTB) {
        int maPhieu = 1;
        if(listCTB.size() == 0) {
            maPhieu = 1;
        } else {
            maPhieu = listCTB.get(listCTB.size() - 1).getMaPhieu() + 1;
        }
        return maPhieu;
    }
    
    private void thietLapBanDau() {
        thietBiService = new ThietBiService();
        quanLyThietBiService = new QuanLyThietBiService();
        phongService = new PhongService();
        chuyenThietBiService = new ChuyenThietBiService();
        
        listPhong = phongService.getAllPhongs();
        listTB = thietBiService.getAllThietBis();
        
        int maPhieu = setNewMaPhieu(chuyenThietBiService.getAllChuyenTBs());
        maPhieuTF.setText(""+maPhieu);
        listPhong.forEach(p -> {
            maPhongCuCbb.addItem(p.getMaPhong());
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        quayLaiButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        maPhieuTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        maPhongCuCbb = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        maTBCbb = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        soLuongSp = new javax.swing.JSpinner();
        tenTBTF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        maPhongMoiCbb = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        ngayChuyenDC = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ghiChuTA = new javax.swing.JTextArea();
        chuyenButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        chuyenTBTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chuyển Thiết Bị");

        quayLaiButton.setBackground(new java.awt.Color(0, 0, 102));
        quayLaiButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        quayLaiButton.setForeground(new java.awt.Color(255, 255, 255));
        quayLaiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Exit.png"))); // NOI18N
        quayLaiButton.setText("Quay Lại");
        quayLaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quayLaiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quayLaiButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(quayLaiButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Mã Phiếu:");

        maPhieuTF.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("Mã Phòng Cũ: ");

        maPhongCuCbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maPhongCuCbbActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("Mã TB:");

        maTBCbb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                maTBCbbFocusLost(evt);
            }
        });
        maTBCbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maTBCbbActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("Tên TB:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText("Số Lượng:");

        soLuongSp.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        tenTBTF.setEditable(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 102));
        jLabel15.setText("Mã Phòng Mới:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 102));
        jLabel16.setText("Ngày Chuyển:");

        ngayChuyenDC.setDateFormatString("yyyy-MM-dd");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 102));
        jLabel17.setText("Ghi Chú:");

        ghiChuTA.setColumns(20);
        ghiChuTA.setRows(5);
        jScrollPane2.setViewportView(ghiChuTA);

        chuyenButton.setBackground(new java.awt.Color(0, 0, 102));
        chuyenButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chuyenButton.setForeground(new java.awt.Color(255, 255, 255));
        chuyenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Tick.png"))); // NOI18N
        chuyenButton.setText("Chuyển");
        chuyenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chuyenButtonActionPerformed(evt);
            }
        });

        refreshButton.setBackground(new java.awt.Color(0, 0, 102));
        refreshButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        refreshButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
        refreshButton.setText("Refresh");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(41, 41, 41)
                        .addComponent(maPhieuTF))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maPhongCuCbb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(maTBCbb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(chuyenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(maPhongMoiCbb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tenTBTF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addGap(9, 9, 9))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(soLuongSp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ngayChuyenDC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(refreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(maPhieuTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(maPhongCuCbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(tenTBTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(maTBCbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(soLuongSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(maPhongMoiCbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16))
                            .addComponent(ngayChuyenDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chuyenButton)
                    .addComponent(refreshButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        chuyenTBTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scroll.setViewportView(chuyenTBTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quayLaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quayLaiButtonActionPerformed
        // TODO add your handling code here:
        this.dispose(); 
    }//GEN-LAST:event_quayLaiButtonActionPerformed

    private void maPhongCuCbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maPhongCuCbbActionPerformed
        // TODO add your handling code here:
        int maPhong = Integer.parseInt(String.valueOf(maPhongCuCbb.getSelectedItem()));
        
        listPhong = phongService.getAllPhongs();
        listQLTB = quanLyThietBiService.getAllQLTBs();
        
        maPhongMoiCbb.removeAllItems();
        listPhong.forEach(p -> {
            maPhongMoiCbb.addItem(p.getMaPhong());
        });
        maPhongMoiCbb.removeItem(maPhong);
        
        maTBCbb.removeAllItems();
        listQLTB.forEach(qltb -> {
            if(qltb.getMaPhong() == maPhong) {
                maTBCbb.addItem(qltb.getMaTB());
            }
        });
        
        
    }//GEN-LAST:event_maPhongCuCbbActionPerformed

    private void maTBCbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maTBCbbActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_maTBCbbActionPerformed

    private void maTBCbbFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_maTBCbbFocusLost
        // TODO add your handling code here:
        int maPhong = Integer.parseInt(String.valueOf(maPhongCuCbb.getSelectedItem()));
        String maTB = String.valueOf(maTBCbb.getSelectedItem());
        if(maTB != null) {
            tB = thietBiService.getTBByMaTB(maTB);
            qLTB = quanLyThietBiService.getQLTBByMaTB(maTB, maPhong);
            tenTBTF.setText(tB.getTenTB());
            int soLuong = qLTB.getSoLuong();
            
            SpinnerModel spinnerModel = new SpinnerNumberModel(1,1,soLuong,1);
            soLuongSp.setModel(spinnerModel);
        }
    }//GEN-LAST:event_maTBCbbFocusLost

    private void chuyenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chuyenButtonActionPerformed
        // TODO add your handling code here:
        int maPhieu = Integer.parseInt(maPhieuTF.getText());
        int maPhongCu = Integer.parseInt(String.valueOf(maPhongCuCbb.getSelectedItem()));
        int maPhongMoi = Integer.parseInt(String.valueOf(maPhongMoiCbb.getSelectedItem()));
        String maTB = String.valueOf(maTBCbb.getSelectedItem());
        int soLuong = Integer.parseInt(String.valueOf(soLuongSp.getValue()));
        String ghiChu = ghiChuTA.getText();
        Date ngayChuyen = ngayChuyenDC.getDate();
        
//        Xét tăng giảm số lượng trong phòng mới và phòng cũ
boolean isTrue = false;
        listQLTB = quanLyThietBiService.getAllQLTBs();
        for(QuanLyThietBi qltb : listQLTB) {
//            Xử lý phòng cũ, nếu số lượng còn lại = 0 thì xoá luôn, còn không thì giảm số lượng
            if(qltb.getMaPhong() == maPhongCu && qltb.getMaTB().equals(maTB)) {
                if(qltb.getSoLuong() - soLuong == 0) {
                    quanLyThietBiService.removeQLTB(qltb);
                } else {
                    qltb.setSoLuong(qltb.getSoLuong() - soLuong);
                }
                
                quanLyThietBiService.updateQLTB(qltb);
            }
//            Xử lý phòng mới, nếu đã có thiết bị đó thì tăng số lượng lên, còn không thì insert mới vào
            if(qltb.getMaPhong() == maPhongMoi) {
                isTrue = true;
                if(qltb.getMaTB().equals(maTB)) {
                    qltb.setSoLuong(qltb.getSoLuong() + soLuong);
                    quanLyThietBiService.updateQLTB(qltb);
                } else {
                    qLTB = new QuanLyThietBi(maPhongMoi, soLuong, maTB, maQL, "", ngayChuyen, ngayChuyen);
                    quanLyThietBiService.insertQLTB(qLTB);
                }
            }
            
        };
//            Nếu phòng đó chưa có thiết bị thì thêm phòng đó vào
        if(!isTrue) {
            qLTB = new QuanLyThietBi(maPhongMoi, soLuong, maTB, maQL, "", ngayChuyen, ngayChuyen);
            quanLyThietBiService.insertQLTB(qLTB);
        }
        cTB = new ChuyenThietBi(maPhieu, maPhongCu, soLuong, maPhongMoi, maTB, ghiChu, ngayChuyen);
        chuyenThietBiService.insertCTB(cTB);
        JOptionPane.showMessageDialog(rootPane, "Chuyển thiết bị thành công!");
        setTableCTB();
    }//GEN-LAST:event_chuyenButtonActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chuyenButton;
    private javax.swing.JTable chuyenTBTable;
    private javax.swing.JTextArea ghiChuTA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField maPhieuTF;
    private javax.swing.JComboBox<Integer> maPhongCuCbb;
    private javax.swing.JComboBox<Integer> maPhongMoiCbb;
    private javax.swing.JComboBox<String> maTBCbb;
    private com.toedter.calendar.JDateChooser ngayChuyenDC;
    private javax.swing.JButton quayLaiButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JSpinner soLuongSp;
    private javax.swing.JTextField tenTBTF;
    // End of variables declaration//GEN-END:variables
}
