/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Admin
 */
public class DoanhThuJframe extends javax.swing.JFrame {

    /**
     * Creates new form DoanhThuJframe
     */
    public DoanhThuJframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JpanelThuChi = new javax.swing.JPanel();
        thuChiLabel = new javax.swing.JLabel();
        JpanelTKPhong = new javax.swing.JPanel();
        tKPhongLabel = new javax.swing.JLabel();
        JpanelTKDoanhThu = new javax.swing.JPanel();
        tKDoanhThuLabel = new javax.swing.JLabel();
        JpanelTKKyLuat = new javax.swing.JPanel();
        tKKyLuatLabel = new javax.swing.JLabel();
        JpanelTKSinhVien = new javax.swing.JPanel();
        tKSinhVienLabel = new javax.swing.JLabel();
        JpanelQLTaiKhoan = new javax.swing.JPanel();
        quanLyTaiKhoanLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        thuChiPanel = new javax.swing.JPanel();
        tKThuChiPanel = new javax.swing.JPanel();
        tKSinhVienPanel = new javax.swing.JPanel();
        tKPhongPanel = new javax.swing.JPanel();
        tKKyLuatPanel = new javax.swing.JPanel();
        quanLyTaiKhoanPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setForeground(new java.awt.Color(0, 0, 102));

        jPanel4.setBackground(new java.awt.Color(255, 208, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THỐNG KÊ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JpanelThuChi.setBackground(new java.awt.Color(255, 208, 75));

        thuChiLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        thuChiLabel.setForeground(new java.awt.Color(0, 0, 102));
        thuChiLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Price list.png"))); // NOI18N
        thuChiLabel.setText("Thu Chi");

        javax.swing.GroupLayout JpanelThuChiLayout = new javax.swing.GroupLayout(JpanelThuChi);
        JpanelThuChi.setLayout(JpanelThuChiLayout);
        JpanelThuChiLayout.setHorizontalGroup(
            JpanelThuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelThuChiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(thuChiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JpanelThuChiLayout.setVerticalGroup(
            JpanelThuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelThuChiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(thuChiLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JpanelTKPhong.setBackground(new java.awt.Color(255, 208, 75));

        tKPhongLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tKPhongLabel.setForeground(new java.awt.Color(0, 0, 102));
        tKPhongLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Home.png"))); // NOI18N
        tKPhongLabel.setText("Thống Kê Phòng");

        javax.swing.GroupLayout JpanelTKPhongLayout = new javax.swing.GroupLayout(JpanelTKPhong);
        JpanelTKPhong.setLayout(JpanelTKPhongLayout);
        JpanelTKPhongLayout.setHorizontalGroup(
            JpanelTKPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelTKPhongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tKPhongLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JpanelTKPhongLayout.setVerticalGroup(
            JpanelTKPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelTKPhongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tKPhongLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JpanelTKDoanhThu.setBackground(new java.awt.Color(255, 208, 75));

        tKDoanhThuLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tKDoanhThuLabel.setForeground(new java.awt.Color(0, 0, 102));
        tKDoanhThuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dollar.png"))); // NOI18N
        tKDoanhThuLabel.setText("Thống Kê Doanh Thu");

        javax.swing.GroupLayout JpanelTKDoanhThuLayout = new javax.swing.GroupLayout(JpanelTKDoanhThu);
        JpanelTKDoanhThu.setLayout(JpanelTKDoanhThuLayout);
        JpanelTKDoanhThuLayout.setHorizontalGroup(
            JpanelTKDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelTKDoanhThuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tKDoanhThuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        JpanelTKDoanhThuLayout.setVerticalGroup(
            JpanelTKDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelTKDoanhThuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tKDoanhThuLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JpanelTKKyLuat.setBackground(new java.awt.Color(255, 208, 75));

        tKKyLuatLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tKKyLuatLabel.setForeground(new java.awt.Color(0, 0, 102));
        tKKyLuatLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Favourites.png"))); // NOI18N
        tKKyLuatLabel.setText("Thống Kê Kỷ Luật");

        javax.swing.GroupLayout JpanelTKKyLuatLayout = new javax.swing.GroupLayout(JpanelTKKyLuat);
        JpanelTKKyLuat.setLayout(JpanelTKKyLuatLayout);
        JpanelTKKyLuatLayout.setHorizontalGroup(
            JpanelTKKyLuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelTKKyLuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tKKyLuatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JpanelTKKyLuatLayout.setVerticalGroup(
            JpanelTKKyLuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelTKKyLuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tKKyLuatLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JpanelTKSinhVien.setBackground(new java.awt.Color(255, 208, 75));

        tKSinhVienLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tKSinhVienLabel.setForeground(new java.awt.Color(0, 0, 102));
        tKSinhVienLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Users.png"))); // NOI18N
        tKSinhVienLabel.setText("Thống Kê Sinh Viên");

        javax.swing.GroupLayout JpanelTKSinhVienLayout = new javax.swing.GroupLayout(JpanelTKSinhVien);
        JpanelTKSinhVien.setLayout(JpanelTKSinhVienLayout);
        JpanelTKSinhVienLayout.setHorizontalGroup(
            JpanelTKSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelTKSinhVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tKSinhVienLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JpanelTKSinhVienLayout.setVerticalGroup(
            JpanelTKSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelTKSinhVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tKSinhVienLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        JpanelQLTaiKhoan.setBackground(new java.awt.Color(255, 208, 75));

        quanLyTaiKhoanLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        quanLyTaiKhoanLabel.setForeground(new java.awt.Color(0, 0, 102));
        quanLyTaiKhoanLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/User.png"))); // NOI18N
        quanLyTaiKhoanLabel.setText("Quản Lý Tài Khoản");

        javax.swing.GroupLayout JpanelQLTaiKhoanLayout = new javax.swing.GroupLayout(JpanelQLTaiKhoan);
        JpanelQLTaiKhoan.setLayout(JpanelQLTaiKhoanLayout);
        JpanelQLTaiKhoanLayout.setHorizontalGroup(
            JpanelQLTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelQLTaiKhoanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quanLyTaiKhoanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JpanelQLTaiKhoanLayout.setVerticalGroup(
            JpanelQLTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelQLTaiKhoanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quanLyTaiKhoanLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        logoutButton.setBackground(new java.awt.Color(255, 208, 19));
        logoutButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(0, 0, 102));
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Exit.png"))); // NOI18N
        logoutButton.setText("Log Out");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JpanelTKDoanhThu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JpanelTKKyLuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JpanelTKPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JpanelThuChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JpanelTKSinhVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JpanelQLTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(logoutButton)))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JpanelThuChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JpanelTKDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JpanelTKSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JpanelTKPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JpanelTKKyLuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JpanelQLTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout thuChiPanelLayout = new javax.swing.GroupLayout(thuChiPanel);
        thuChiPanel.setLayout(thuChiPanelLayout);
        thuChiPanelLayout.setHorizontalGroup(
            thuChiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        thuChiPanelLayout.setVerticalGroup(
            thuChiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout tKThuChiPanelLayout = new javax.swing.GroupLayout(tKThuChiPanel);
        tKThuChiPanel.setLayout(tKThuChiPanelLayout);
        tKThuChiPanelLayout.setHorizontalGroup(
            tKThuChiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        tKThuChiPanelLayout.setVerticalGroup(
            tKThuChiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout tKSinhVienPanelLayout = new javax.swing.GroupLayout(tKSinhVienPanel);
        tKSinhVienPanel.setLayout(tKSinhVienPanelLayout);
        tKSinhVienPanelLayout.setHorizontalGroup(
            tKSinhVienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        tKSinhVienPanelLayout.setVerticalGroup(
            tKSinhVienPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout tKPhongPanelLayout = new javax.swing.GroupLayout(tKPhongPanel);
        tKPhongPanel.setLayout(tKPhongPanelLayout);
        tKPhongPanelLayout.setHorizontalGroup(
            tKPhongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        tKPhongPanelLayout.setVerticalGroup(
            tKPhongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout tKKyLuatPanelLayout = new javax.swing.GroupLayout(tKKyLuatPanel);
        tKKyLuatPanel.setLayout(tKKyLuatPanelLayout);
        tKKyLuatPanelLayout.setHorizontalGroup(
            tKKyLuatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        tKKyLuatPanelLayout.setVerticalGroup(
            tKKyLuatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout quanLyTaiKhoanPanelLayout = new javax.swing.GroupLayout(quanLyTaiKhoanPanel);
        quanLyTaiKhoanPanel.setLayout(quanLyTaiKhoanPanelLayout);
        quanLyTaiKhoanPanelLayout.setHorizontalGroup(
            quanLyTaiKhoanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        quanLyTaiKhoanPanelLayout.setVerticalGroup(
            quanLyTaiKhoanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(quanLyTaiKhoanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(thuChiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tKThuChiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tKPhongPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tKSinhVienPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tKKyLuatPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(quanLyTaiKhoanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(thuChiPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tKThuChiPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tKPhongPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tKSinhVienPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tKKyLuatPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoanhThuJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoanhThuJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoanhThuJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoanhThuJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoanhThuJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpanelQLTaiKhoan;
    private javax.swing.JPanel JpanelTKDoanhThu;
    private javax.swing.JPanel JpanelTKKyLuat;
    private javax.swing.JPanel JpanelTKPhong;
    private javax.swing.JPanel JpanelTKSinhVien;
    private javax.swing.JPanel JpanelThuChi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel quanLyTaiKhoanLabel;
    private javax.swing.JPanel quanLyTaiKhoanPanel;
    private javax.swing.JLabel tKDoanhThuLabel;
    private javax.swing.JLabel tKKyLuatLabel;
    private javax.swing.JPanel tKKyLuatPanel;
    private javax.swing.JLabel tKPhongLabel;
    private javax.swing.JPanel tKPhongPanel;
    private javax.swing.JLabel tKSinhVienLabel;
    private javax.swing.JPanel tKSinhVienPanel;
    private javax.swing.JPanel tKThuChiPanel;
    private javax.swing.JLabel thuChiLabel;
    private javax.swing.JPanel thuChiPanel;
    // End of variables declaration//GEN-END:variables
}
