/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import BEANS.Phong;
import BEANS.QuanLyThietBi;
import BEANS.ThietBi;
import Controller.PhongService;
import Controller.QuanLyThietBiService;
import Controller.ThietBiService;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Admin
 */
public class ThietBiPhongJframe extends javax.swing.JFrame {
//    Thiết bị

    ThietBiService thietBiService;
    ThietBi tB;
    List<ThietBi> listTB;

//  Quản lý thiết bị
    QuanLyThietBiService quanLyThietBiService;
    QuanLyThietBi qLTB;
    List<QuanLyThietBi> listQLTB;
    DefaultTableModel defautQLTBModel;

//    Phòng:
    PhongService phongService;
    Phong p;
    List<Phong> listP;

    String maQL;

    /**
     * Creates new form VatTuPhongJframe
     */
    public ThietBiPhongJframe(String maQL1) {
        initComponents();

        thietBiService = new ThietBiService();
        quanLyThietBiService = new QuanLyThietBiService();

        listTB = thietBiService.getAllThietBis();
        setTableTB();
        
        phongService = new PhongService();
        listP = phongService.getAllPhongs();
        listP.forEach(p -> {
            maPhongCbb.addItem(p.getMaPhong());
        });

        listQLTB = quanLyThietBiService.getAllQLTBs();
        listTB.forEach(tB -> {
            if (soLuongConLai(tB.getMaTB(), listQLTB) != 0) {
                maTBCbb.addItem(tB.getMaTB());
            }
        });

        luuLaiButton.setVisible(false);
        maQLTBTF.setText(maQL);
        maQL = maQL1;
        maQLTBTF.setText(maQL);

    }

    private void setTableTB() {
        defautQLTBModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        TableRowSorter<DefaultTableModel> sorterTB = new TableRowSorter<DefaultTableModel>(defautQLTBModel);
        thietBiTable.setRowSorter(sorterTB);


        thietBiTable.setModel(defautQLTBModel);
        defautQLTBModel.addColumn("Mã Phòng");
        defautQLTBModel.addColumn("Mã TB");
        defautQLTBModel.addColumn("Tên TB");
        defautQLTBModel.addColumn("Loại TB");
        defautQLTBModel.addColumn("Tình Trạng");
        defautQLTBModel.addColumn("Số Lượng");
        defautQLTBModel.addColumn("Ngày Bàn Giao");
        defautQLTBModel.addColumn("Ngày Kiểm Tra");
        defautQLTBModel.addColumn("Mã QL");
        defautQLTBModel.addColumn("Ghi Chú");

        setAllDataTB(quanLyThietBiService.getAllQLTBs());

    }

    private void setAllDataTB(List<QuanLyThietBi> listQLTB) {
        defautQLTBModel.setRowCount(0);
        listQLTB.forEach(qLTB -> {
            tB = thietBiService.getTBByMaTB(qLTB.getMaTB());
            defautQLTBModel.addRow(new Object[]{
                qLTB.getMaPhong(), qLTB.getMaTB(), tB.getTenTB(), tB.getLoaiTB(), tB.getTinhTrang(), qLTB.getSoLuong(), qLTB.getNgayBanGiao(), qLTB.getNgayKiemTra(), qLTB.getMaQL(), qLTB.getGhiChu()
            });

        });
    }

    private void setDataTB(List<QuanLyThietBi> listQLTB, int maPhong) {
        defautQLTBModel.setRowCount(0);
        listQLTB.forEach(qLTB -> {
            if (qLTB.getMaPhong() == maPhong) {
                tB = thietBiService.getTBByMaTB(qLTB.getMaTB());
                defautQLTBModel.addRow(new Object[]{
                    qLTB.getMaPhong(), qLTB.getMaTB(), tB.getTenTB(), tB.getLoaiTB(), tB.getTinhTrang(), qLTB.getSoLuong(), qLTB.getNgayBanGiao(), qLTB.getNgayKiemTra(), qLTB.getMaQL(), qLTB.getGhiChu()
                });
            }
        });
    }

    private int soLuongConLai(String maTB, List<QuanLyThietBi> listQLTB) {
        tB = thietBiService.getTBByMaTB(maTB);
        int soLuongTong = tB.getSoLuong();

        listQLTB = quanLyThietBiService.getAllQLTBs();
        int soLuongDaDung = 0;
        for (QuanLyThietBi qLTB : listQLTB) {
            if (qLTB.getMaTB().equals(maTB)) {
                soLuongDaDung += qLTB.getSoLuong();
            }
        }
        int soLuongConLai = soLuongTong - soLuongDaDung;
        return soLuongConLai;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        quayLaiButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tenTBTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        soLuongTBSp = new javax.swing.JSpinner();
        tinhTrangTBCbb = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ngayBanGiaoDC = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        ghiChuTBTA = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        maTBCbb = new javax.swing.JComboBox<>();
        themTBButton = new javax.swing.JButton();
        capNhapTBButton = new javax.swing.JButton();
        xoaTBButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ngayKiemTraDC = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        maQLTBTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        loaiTBCbb = new javax.swing.JComboBox<>();
        refreshButton = new javax.swing.JButton();
        luuLaiButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        maPhongCbb = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        sLConLaiTF = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        thietBiTable = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        chuyenTBButton = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        themTBTongButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý thiết bị vật tư trong phòng");

        quayLaiButton.setBackground(new java.awt.Color(0, 0, 102));
        quayLaiButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        quayLaiButton.setForeground(new java.awt.Color(255, 255, 255));
        quayLaiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Exit.png"))); // NOI18N
        quayLaiButton.setText("Quay Lại");
        quayLaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quayLaiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quayLaiButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(quayLaiButton))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Mã Phòng");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Tên TB:");

        tenTBTF.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Số Lượng");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Tình Trạng");

        soLuongTBSp.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        tinhTrangTBCbb.setEditable(true);
        tinhTrangTBCbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mới", "Cũ", "Hư hỏng" }));
        tinhTrangTBCbb.setToolTipText("");
        tinhTrangTBCbb.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Ghi Chú:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Ngày Bàn Giao:");

        ngayBanGiaoDC.setDateFormatString("yyyy-MM-dd");

        ghiChuTBTA.setColumns(20);
        ghiChuTBTA.setRows(5);
        jScrollPane1.setViewportView(ghiChuTBTA);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Mã TB:");

        maTBCbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maTBCbbActionPerformed(evt);
            }
        });

        themTBButton.setBackground(new java.awt.Color(0, 0, 102));
        themTBButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        themTBButton.setForeground(new java.awt.Color(255, 255, 255));
        themTBButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        themTBButton.setText("Thêm");
        themTBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themTBButtonActionPerformed(evt);
            }
        });

        capNhapTBButton.setBackground(new java.awt.Color(0, 0, 102));
        capNhapTBButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        capNhapTBButton.setForeground(new java.awt.Color(255, 255, 255));
        capNhapTBButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit.png"))); // NOI18N
        capNhapTBButton.setText("Cập Nhập");
        capNhapTBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capNhapTBButtonActionPerformed(evt);
            }
        });

        xoaTBButton.setBackground(new java.awt.Color(0, 0, 102));
        xoaTBButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        xoaTBButton.setForeground(new java.awt.Color(255, 255, 255));
        xoaTBButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        xoaTBButton.setText("Xoá");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("Ngày Kiểm Tra:");

        ngayKiemTraDC.setDateFormatString("yyyy-MM-dd");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Mã QL:");

        maQLTBTF.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("Loại TB:");

        loaiTBCbb.setEditable(true);
        loaiTBCbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tủ", "Giường", "Quạt", "Vệ Sinh", "Đèn" }));
        loaiTBCbb.setEnabled(false);

        refreshButton.setBackground(new java.awt.Color(0, 0, 102));
        refreshButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        refreshButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        luuLaiButton.setBackground(new java.awt.Color(0, 0, 102));
        luuLaiButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        luuLaiButton.setForeground(new java.awt.Color(255, 255, 255));
        luuLaiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Save.png"))); // NOI18N
        luuLaiButton.setText("Lưu Lại");
        luuLaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuLaiButtonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("SL Còn Lại:");

        sLConLaiTF.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(themTBButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(luuLaiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(maPhongCbb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tenTBTF, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(maTBCbb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel11)
                                .addGap(35, 35, 35)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loaiTBCbb, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tinhTrangTBCbb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(sLConLaiTF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(soLuongTBSp)
                    .addComponent(maQLTBTF)
                    .addComponent(capNhapTBButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(ngayBanGiaoDC, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(xoaTBButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ngayKiemTraDC, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(refreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(maTBCbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(sLConLaiTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(soLuongTBSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel5)
                                .addComponent(tinhTrangTBCbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(maPhongCbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addComponent(ngayBanGiaoDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ngayKiemTraDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tenTBTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(maQLTBTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel3)
                                .addComponent(jLabel11)
                                .addComponent(loaiTBCbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(capNhapTBButton)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(themTBButton)
                        .addComponent(xoaTBButton)
                        .addComponent(refreshButton)
                        .addComponent(luuLaiButton)))
                .addContainerGap())
        );

        thietBiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        thietBiTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        thietBiTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thietBiTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(thietBiTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar1.setRollover(true);

        chuyenTBButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chuyenTBButton.setForeground(new java.awt.Color(0, 0, 102));
        chuyenTBButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add to basket.png"))); // NOI18N
        chuyenTBButton.setText("Chuyển Thiết Bị");
        chuyenTBButton.setFocusable(false);
        chuyenTBButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chuyenTBButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        chuyenTBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chuyenTBButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(chuyenTBButton);
        jToolBar1.add(jSeparator5);

        themTBTongButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        themTBTongButton.setForeground(new java.awt.Color(0, 0, 102));
        themTBTongButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        themTBTongButton.setText("Thêm Thiết Bị");
        themTBTongButton.setFocusable(false);
        themTBTongButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        themTBTongButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        themTBTongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themTBTongButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(themTBTongButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void thietBiTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thietBiTableMouseClicked
        // TODO add your handling code here:
        luuLaiButton.setVisible(false);
        loaiTBCbb.removeActionListener(loaiTBCbb);
        int row = thietBiTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn trường");
        } else {
            int maPhong = Integer.parseInt(String.valueOf(thietBiTable.getValueAt(row, 0)));
            String maTB = String.valueOf(thietBiTable.getValueAt(row, 1));
            tB = thietBiService.getTBByMaTB(maTB);
            qLTB = quanLyThietBiService.getQLTBByMaTB(maTB, maPhong);

            maTBCbb.setSelectedItem(tB.getMaTB());
            tenTBTF.setText(tB.getTenTB());
            soLuongTBSp.setValue(qLTB.getSoLuong());
            tinhTrangTBCbb.setSelectedItem(tB.getTinhTrang());
            ghiChuTBTA.setText(qLTB.getGhiChu());
            ngayBanGiaoDC.setDate(qLTB.getNgayBanGiao());
            ngayKiemTraDC.setDate(qLTB.getNgayKiemTra());
            maPhongCbb.setSelectedItem(qLTB.getMaPhong());
            maQLTBTF.setText(qLTB.getMaQL());
            loaiTBCbb.setSelectedItem(tB.getLoaiTB());

            tinhTrangTBCbb.setEnabled(true);
//            Xét số lượng tối đa có thể sửa sau khi click
            int soLuongConLai = soLuongConLai(maTB, quanLyThietBiService.getAllQLTBs());
            SpinnerModel spinnerModel;
            if (soLuongConLai == 0) {
                spinnerModel = new SpinnerNumberModel(qLTB.getSoLuong(), 1, qLTB.getSoLuong(), 1);
            } else {
                spinnerModel = new SpinnerNumberModel(qLTB.getSoLuong(), 1, (qLTB.getSoLuong() + soLuongConLai), 1);
            }
            soLuongTBSp.setModel(spinnerModel);
            sLConLaiTF.setText("" + soLuongConLai);
        }
    }//GEN-LAST:event_thietBiTableMouseClicked

    private void themTBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themTBButtonActionPerformed
        // TODO add your handling code here:
        maTBCbbActionPerformed(evt);
        loaiTBCbb.setEnabled(false);
        String maTB = String.valueOf(maTBCbb.getSelectedItem());

        int soLuongConLai = soLuongConLai(maTB, quanLyThietBiService.getAllQLTBs());
        if (soLuongConLai == 0) {
            JOptionPane.showMessageDialog(rootPane, "Thiết bị này đã hết trong kho! Không thể thêm vào phòng");
        } else {
            luuLaiButton.setVisible(true);
            SpinnerModel spinnerModel = new SpinnerNumberModel(1, 1, soLuongConLai, 1);
            soLuongTBSp.setModel(spinnerModel);
        }
    }//GEN-LAST:event_themTBButtonActionPerformed

    private void capNhapTBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capNhapTBButtonActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn sửa không?");
        if (confirm == JOptionPane.YES_OPTION) {
            int row = thietBiTable.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn trường cần sửa");
            } else {
                int maPhong = Integer.parseInt(String.valueOf(thietBiTable.getValueAt(row, 0)));
                String maTB = String.valueOf(thietBiTable.getValueAt(row, 1));
                int soLuong = Integer.parseInt(String.valueOf(soLuongTBSp.getValue()));
                String tinhTrang = String.valueOf(tinhTrangTBCbb.getSelectedItem());
                String ghiChu = ghiChuTBTA.getText();
                Date ngayKiemTra = ngayKiemTraDC.getDate();

//                Xét lại các thuộc tính của quản lý thiết bị và thiết bị
                qLTB = quanLyThietBiService.getQLTBByMaTB(maTB, maPhong);
                tB = thietBiService.getTBByMaTB(maTB);

                tB.setTinhTrang(tinhTrang);

                qLTB.setSoLuong(soLuong);
                qLTB.setNgayKiemTra(ngayKiemTra);
                qLTB.setGhiChu(ghiChu);

////                Xét lại số lượng tổng
//                int soLuongTong = 0;
//                if(soLuong > qLTB.getSoLuong()) {
//                    soLuongTong = (tB.getSoLuong() + (soLuong - qLTB.getSoLuong()));
//                } else if(soLuong < qLTB.getSoLuong()){
//                    soLuongTong = (tB.getSoLuong() - (qLTB.getSoLuong() - soLuong));
//                }
                thietBiService.updateThietBi(tB);
                quanLyThietBiService.updateQLTB(qLTB);
                setTableTB();

            }
        }
    }//GEN-LAST:event_capNhapTBButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        maPhongCbb.setSelectedIndex(0);
        tenTBTF.setText("");
        tinhTrangTBCbb.setSelectedIndex(0);
        soLuongTBSp.setValue(1);
        ghiChuTBTA.setText("");
        luuLaiButton.setVisible(false);
        tinhTrangTBCbb.setEnabled(false);
        setTableTB();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void luuLaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuLaiButtonActionPerformed
        // TODO add your handling code here:
        String maTB = String.valueOf(maTBCbb.getSelectedItem());
        String tenTB = tenTBTF.getText();
        int soLuong = Integer.parseInt(String.valueOf(soLuongTBSp.getValue()));
        String tinhTrang = String.valueOf(tinhTrangTBCbb.getSelectedItem());
        String ghiChu = ghiChuTBTA.getText();
        Date ngayBanGiao = ngayBanGiaoDC.getDate();
        Date ngayKiemTra = ngayKiemTraDC.getDate();
        int maPhong = Integer.parseInt(String.valueOf(maPhongCbb.getSelectedItem()));
        String maQL = maQLTBTF.getText();
        String loaiTb = String.valueOf(loaiTBCbb.getSelectedItem());

        listQLTB = quanLyThietBiService.getAllQLTBs();
        boolean isContinue = true;
        for (QuanLyThietBi qltb : listQLTB) {
            if (qltb.getMaTB().equals(maTB) && qltb.getMaPhong() == maPhong) {
                qltb.setSoLuong(qltb.getSoLuong() + soLuong);
                quanLyThietBiService.updateQLTB(qltb);
                isContinue = false;
            }
        }
        if (isContinue) {
            qLTB = new QuanLyThietBi(maPhong, soLuong, maTB, maQL, ghiChu, ngayBanGiao, ngayKiemTra);
            quanLyThietBiService.insertQLTB(qLTB);
        }
        JOptionPane.showMessageDialog(rootPane, "Thêm thiết bị vào phòng thành công!");
        refreshButtonActionPerformed(evt);

    }//GEN-LAST:event_luuLaiButtonActionPerformed

    private void chuyenTBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chuyenTBButtonActionPerformed
        // TODO add your handling code here:
        int row = thietBiTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn thiết bị để chuyển");
        } else {
            String maTB = String.valueOf(thietBiTable.getValueAt(row, 1));
            int maPhong = Integer.parseInt(String.valueOf(thietBiTable.getValueAt(row, 0)));
            new ChuyenThietBiJframe(maTB, "QL001", maPhong).setVisible(true);
        }
    }//GEN-LAST:event_chuyenTBButtonActionPerformed

    private void maTBCbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maTBCbbActionPerformed
        // TODO add your handling code here:
        String maTB = String.valueOf(maTBCbb.getSelectedItem());
        tB = thietBiService.getTBByMaTB(maTB);
        int sLCon = soLuongConLai(maTB, quanLyThietBiService.getAllQLTBs());
        sLConLaiTF.setText("" + sLCon);
        SpinnerModel spinner = new SpinnerNumberModel(1, 1, sLCon, 1);
        soLuongTBSp.setModel(spinner);

        tenTBTF.setText(tB.getTenTB());
        tinhTrangTBCbb.setSelectedItem(tB.getTinhTrang());
        loaiTBCbb.setSelectedItem(tB.getLoaiTB());
    }//GEN-LAST:event_maTBCbbActionPerformed

    private void themTBTongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themTBTongButtonActionPerformed
        // TODO add your handling code here:
        new ThemThietBiJframe(maQL).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_themTBTongButtonActionPerformed

    private void quayLaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quayLaiButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_quayLaiButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton capNhapTBButton;
    private javax.swing.JButton chuyenTBButton;
    private javax.swing.JTextArea ghiChuTBTA;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JComboBox<String> loaiTBCbb;
    private javax.swing.JButton luuLaiButton;
    private javax.swing.JComboBox<Integer> maPhongCbb;
    private javax.swing.JTextField maQLTBTF;
    private javax.swing.JComboBox<String> maTBCbb;
    private com.toedter.calendar.JDateChooser ngayBanGiaoDC;
    private com.toedter.calendar.JDateChooser ngayKiemTraDC;
    private javax.swing.JButton quayLaiButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTextField sLConLaiTF;
    private javax.swing.JSpinner soLuongTBSp;
    private javax.swing.JTextField tenTBTF;
    private javax.swing.JButton themTBButton;
    private javax.swing.JButton themTBTongButton;
    private javax.swing.JTable thietBiTable;
    private javax.swing.JComboBox<String> tinhTrangTBCbb;
    private javax.swing.JButton xoaTBButton;
    // End of variables declaration//GEN-END:variables
}
